### PR TITLE
Add Pypi support - Closes #276

### LINKED ISSUE #276: PyPI Packaging
Are there any plans to package this app up to be installed using something like `pip` in order to make the installation process very simple?

### PR DESCRIPTION
**Pull request by kevgliss**
Still running into a few build errors on OS X and need to test on ubuntu.

### CODE REVIEW

**Comment by westlifezs** [comment]
We found out that you created a PR for security monkey easy install.
We like this feature a lot and this is really what we want now.
I am able to build security monkey through the online instruction successfully.


We also tried to use "pip install security_monkey" to build security monkey.
I can have "/usr/local/lib/python2.7/dist-packages/security_monkey" created.

Then could you please let us know what should we do next?

I did "cd security_monkey; sudo python setup.py install" after "pip install security_monkey".
However, I encountered an error saying:


ubuntu@:~/security_monkey$ sudo python setup.py install
running install
running build_static
getting required dependencies for debian
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1745  100  1745    0     0  26172      0 --:--:-- --:--:-- --:--:-- 26439
E: Invalid operation add
Traceback (most recent call last):
  File "setup.py", line 176, in <module>
    "License :: OSI Approved :: Apache Software License"
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 62, in run
    self.run_command('build_static')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 93, in run
    dart_path = install_dart_debian()
  File "setup.py", line 134, in install_dart_debian
    check_output(['sudo', 'apt-get', 'add', '-'])
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['sudo', 'apt-get', 'add', '-']' returned non-zero exit status 100


Am I missing something here?
Have you seen this error through the easy install build process?

Thanks and look forward to hearing from you.

**Comment by kevgliss** [comment]
First, did you merge this PR into the master branch? It's quite old so I am not sure if things have diverged. I would run the command thats failing `sudo apt-get add -` on the target machine to see if it gives you any errors, I am assuming you're running this on ubuntu?

**Comment by westlifezs** [comment]
yes. I am running this on Ubuntu. I run the following cmd for easy install:

git clone https://github.com/Netflix/security_monkey.git
cd security_monkey/
git fetch origin pull/278/head:easyinstall
git checkout easyinstall
sudo pip install security_monkey

Could you please clarify "I would run the command thats failing sudo apt-get add - on the target machine"?

I tried "sudo apt-get add -" but I saw the following error:

ubuntu@:~$ sudo apt-get add -
E: Invalid operation add

look forward to hearing from you!

**Comment by kevgliss** [comment]
It looks like the command might be a bit wrong. Looking at:

https://www.dartlang.org/downloads/linux.html 

It seems it wants something equivalent to:
 `$ sudo sh -c 'curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'`

Unfortunately check_output doesn't support pipes, so they would need to be converted to [popen](https://docs.python.org/2/library/subprocess.html#subprocess.Popen.communicate).

Alternatively you might also be able simple switch from using `-` (which refers to stdin) to an actual file name, or in this case `linux_signing_key.pub`.

So the second command would look something like:
`check_output(['sudo', 'apt-get', 'add', 'linux_signing_key.pub'])` (untested)

**Comment by westlifezs** [comment]
Kevin,

Could you please elaborate it a little bit?
I do not know what command I need to run for the checking from https://www.dartlang.org/downloads/linux.html

And why do we need to do this key add check to verify easy install?

thanks,

**Comment by westlifezs** [comment]
this is the command I used based on the tutorial and it seems like the key can be successfully installed.
anything else I need to check? thanks

ubuntu@ip-:~$ curl -o linux_signing_key.pub https://dl-ssl.google.com/linux/linux_signing_key.pub
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1745  100  1745    0     0  18165      0 --:--:-- --:--:-- --:--:-- 18368
ubuntu@:~$ ls
linux_signing_key.pub  security_monkey
ubuntu@:~$ sudo apt-key add linux_signing_key.pub
OK
ubuntu@:~$

**Comment by kevgliss** [comment]
I guess I don't understand, the suggestion I mentioned was to fix the existing pull request. You will still presumably need to run the other steps, once you fix that one step, is it throwing a different error? Or are you just trying to install it manually via the documentation?

**Comment by westlifezs** [comment]
Hi Kevin,

 I can successfully install it through documentation.
However, I want to use easy install to simplify the process.

In order to do that, I run

git clone https://github.com/Netflix/security_monkey.git
cd security_monkey/
git fetch origin pull/278/head:easyinstall
git checkout easyinstall
sudo pip install security_monkey

what's the next step/cmd shall run to install it?

I tried "sudo python setup.py install" but I failed with the following error:

running install
running build_static
getting required dependencies for debian
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
100 1745 100 1745 0 0 26172 0 --:--:-- --:--:-- --:--:-- 26439
E: Invalid operation add
Traceback (most recent call last):
File "setup.py", line 176, in 
"License :: OSI Approved :: Apache Software License"
File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
dist.run_commands()
File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
self.run_command(cmd)
File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
cmd_obj.run()
File "setup.py", line 62, in run
self.run_command('build_static')
File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
self.distribution.run_command(command)
File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
cmd_obj.run()
File "setup.py", line 93, in run
dart_path = install_dart_debian()
File "setup.py", line 134, in install_dart_debian
check_output(['sudo', 'apt-get', 'add', '-'])
File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['sudo', 'apt-get', 'add', '-']' returned non-zero exit status 100


Could you please let me know what should I do after I typed "pip install security_monkey" in order to set it up successfully?

thank you

**Comment by westlifezs** [comment]
I think I got your point. I did not look into the source before.
After checking the source. I manually downloaded "linux_signing_key.pub" and changed the second command to "check_output(['sudo', 'apt-get', 'add', 'linux_signing_key.pub'])".

I re-run "sudo python setup.py install"  and hit another error:


running install
running build_static
getting required dependencies for debian
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1745  100  1745    0     0  18457      0 --:--:-- --:--:-- --:--:-- 18563
E: Invalid operation add
Traceback (most recent call last):
  File "setup.py", line 176, in <module>
    "License :: OSI Approved :: Apache Software License"
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 62, in run
    self.run_command('build_static')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 93, in run
    dart_path = install_dart_debian()
  File "setup.py", line 134, in install_dart_debian
    check_output(['sudo', 'apt-get', 'add', 'linux_signing_key.pub'])
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['sudo', 'apt-get', 'add', 'linux_signing_key.pub']' returned non-zero exit status 100


any suggestions?

thanks,

**Comment by westlifezs** [comment]
I also tried a full path file name instead of just "linux_signing_key.pub" but the error remains the same.

**Comment by monkeysecurity** [comment]
Closing for now.  May re-evaluate in future.

**Pull request closed without merging**
