### PR TITLE
Added dictConfig logging format for flexible logging options

### PR DESCRIPTION
**Pull request by crruthe**
This change is useful to quickly add/modify logging handlers, e.g. syslog or remote logging.

We have a custom handler we use internally to push JSON into elasticsearch.

### CODE REVIEW

**Comment by monkeysecurity** [comment]
I probably should have played with this more before merging.

I believe the `@app.before_first_request` means it won't setup logging when being run from the CLI.

So `python manage.py find_changes -m route53` ends up not having any messages.  Manually invoking `setup_logging()` seems to work.

Next problem is that many of the security_monkey watcher logs are output as DEBUG, but setting the root level to DEBUG causes an enormous number of boto logs to obscure security_monkey info.  So probably want the root level to be INFO, but somehow set the flask app to DEBUG.  (OR, upgrade the important security_monkey log messages to INFO.)

**Comment by monkeysecurity** [comment]
May require a more complex LOG_CFG to get the behavior I desire.

```
LOG_CFG = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s %(levelname)s: %(message)s '
                '[in %(pathname)s:%(lineno)d]'
        }
    },
    'handlers': {
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'level': 'DEBUG',
            'formatter': 'standard',
            'filename': '....../securitymonkey.log',
            'maxBytes': 10485760,
            'backupCount': 100,
            'encoding': 'utf8'
        },
        'console': {
            'class': 'logging.StreamHandler',
            'level': 'DEBUG',
            'formatter': 'standard',
            'stream': 'ext://sys.stdout'
        }
    },
    'root': {
        'handlers': ['file', 'console'],
        'level': 'INFO'
    },
    'loggers': {
        'security_monkey': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG'
        },
        'apscheduler': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG'
        } ,
#        'boto': {
#            'handlers': ['file', 'console'],
#            'level': 'ERROR',
#            'propagate': False
#        },
#        'boto3': {
#            'handlers': ['file', 'console'],
#            'level': 'ERROR',
#            'propagate': False
#        },
        'botocore': {
            'handlers': ['file', 'console'],
            'level': 'ERROR',
            'propagate': False
        }
#        'requests': {
#            'handlers': ['file', 'console'],
#            'level': 'ERROR',
#            'propagate': False
#        },
#        'requests.packages.urllib3.connectionpool': {
#            'handlers': ['file', 'console'],
#            'level': 'ERROR',
#            'propagate': False
#        }
    }
}
```

**Comment by crruthe** [comment]
Thanks for persisting with these changes, I definitely missed many aspect 👎 
As you can see, very new to pushing changes to Github.

It looks like Flask's app.logger will remove all your handlers for you (good guy Flask), which causes the logging config to not work as excepted.
This can easily be fixed by added a line above the dictConfig call in `security_monkey/__init__.py`

```
        if app.config.get('LOG_CFG') is not None:
            # initialize the Flask logger (removes all handlers)
            log = app.logger
            dictConfig(app.config.get('LOG_CFG'))
```

Once you have made this change, you can simplify your logging config as expected:
```
LOG_CFG = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s %(levelname)s: %(message)s '
                '[in %(pathname)s:%(lineno)d]'
        }
    },
    'handlers': {
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'formatter': 'standard',
            'filename': '....../securitymonkey.log',
            'maxBytes': 10485760,
            'backupCount': 100,
            'encoding': 'utf8'
        },
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
            'stream': 'ext://sys.stdout'
        }
    },
    'loggers': {
        'security_monkey': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG'
        },
        'apscheduler': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG'
        }
    }
}
```

**Comment by crruthe** [comment]
Also, with respect to the `setup_logging`, I feel like the advantage of using it within a function is diminished and it makes more sense to simply drop it out of the function, making it inline like it was before.

**Comment by monkeysecurity** [comment]
Hey @crruthe - Thanks for the update.  Looks like a good solution.

**Comment by monkeysecurity** [comment]
Just merged in #364 to apply those changes.  Thanks @crruthe.

**Pull request merged**
