### PR TITLE
fix-basestring-unicode-for-Python3-again

### PR DESCRIPTION
**Pull request by cclauss**
The syntax errors in #974 prevented flake8 from finding theses issues or they would have been fixed in #977 so now they will be fixed in this PR.

### CODE REVIEW

**Comment by cclauss** [comment]
Nice progress but further headway blocked until Netflix-Skunkworks/cloudaux#60 or similar is merged.

**Comment by mikegrima** [comment]
Do me a favor and up the version number on this: https://github.com/Netflix-Skunkworks/cloudaux/blob/master/cloudaux/__about__.py

Then I'll merge it to PyPI. Though I'll probably do this on Monday since it's getting late.

**Comment by cclauss** [comment]
Netflix-Skunkworks/cloudaux#64 or similar must be merged to make further progress.

**Comment by cclauss** [comment]
@mikegrima Please review.

**Comment by mikegrima** [comment]
Will look into this now

**Comment by mikegrima** [comment]
CloudAux 1.4.8 pushed to PyPI.  @cclauss You'll need to modify `setup.py` to point to 1.4.8 for CloudAux.

**Comment by mikegrima** [comment]
Pushed 1.4.9 to PyPI.

**Comment by cclauss** [comment]
@mikegrima I think that I have taken this PR as far as I can go without help from someone who really knows the code.  In its current state, the code in this PR passes all of the non-Python3 tests so you might want to review it and check it in.  It would be good if you or someone on your team could either can take over the Python 3 port from here or at least help me understand why the [Python 3 Travis tests are stuck](https://travis-ci.org/Netflix/security_monkey/builds/349464775).

**Comment by mikegrima** [comment]
I'll take a look at this when I have some more time.

**Pull request merged**
