### PR TITLE
[WIP] Upgrade the 'moto' package in setup.py

### PR DESCRIPTION
**Pull request by cclauss**
"[_You should be able to upgrade moto to the latest version. We have a bunch of Python 3 projects that use it without issues._](https://github.com/Netflix/security_monkey/issues/996#issuecomment-372401302)" -- @mikegrima 

https://pypi.python.org/pypi/moto

### CODE REVIEW

**Comment by mikegrima** [comment]
Odd that the tests are failing with the latest moto.

**Comment by mikegrima** [comment]
https://github.com/spulec/moto#using-moto-10x-with-boto2
This is why ^^

**Comment by mikegrima** [comment]
For the S3 test, as it turns out, yours truly actually implemented the missing methods in moto that would previously raise exceptions. So we could actually do proper S3 tests now :)

**Comment by mikegrima** [comment]
@cclauss This might not be as trivial as I thought. Feel free to update the tests yourself, or I can do it (up to you).

**Comment by cclauss** [comment]
I think you had better do it as I am not an AWS guy.

**Pull request closed without merging**
