### PR TITLE
Plugins support

### PR DESCRIPTION
**Pull request by redixin**
Plugins support via entry_points

Closes: #503

### CODE REVIEW

**Comment by redixin** [comment]
Sorry for my bad English in docs. Feel free to fix it. Also I'm not sure how and where to connect docs in index.rst

**Comment by monkeysecurity** [comment]
This looks cool. Thanks @redixin.

**Comment by mariusgrigaitis** [comment]
I like it. Any blockers to get it merged?

**Comment by mikegrima** [comment]
Looks good to me 👍

**Comment by monkeysecurity** [comment]
PR merged! 🔌

**Pull request merged**
