### PR TITLE
Upgrade s3 to boto3

### PR DESCRIPTION
**Pull request by zollman**
Type: generic-bugfix

Why is this change necessary?
The S3 watcher did not handle several error conditions correctly,
resulting in buckets not being displayed:
1) boto issue at https://github.com/Netflix/security_monkey/issues/430
2) Bucket permission issues

This change addresses the need by:
Moving the S3 watcher to the boto3 library and handling the case where
a bucket does not allow the viewing of details

Potential Side Effects:
Boto3 allows for all lifecycle transitions to be returned, so upgrading
to a list

### CODE REVIEW

**Comment by aebie** [comment]
@monkeysecurity a question came in about why we changed the decorator for this PR and we thought this explanation would be helpful:

This method is called by the iter_account_region decorator to determine which regions the technology type should be run against. As a side effect, it also returns the results of the assume role which is stored in the kwargs and is used by subsequent connect requests. This greatly reduces the number of assume role calls made, improving performance and reducing load on aws. While testing this I noticed that this benefit was not gained when we were using a universal technology type because in that case we return before we do the assume role call. Since the s3 watcher contains many calls, I thought it would be helpful performance wise to modify this method so that it could reuse the role.

**Comment by monkeysecurity** [comment]
For the decorator fix: Interesting.

Long term, we may want to get connections from `cloudaux.aws.sts`:
https://github.com/Netflix-Skunkworks/cloudaux/blob/master/cloudaux/aws/sts.py#L46

CloudAux will cache connections until shortly before they expire.

**Comment by monkeysecurity** [comment]
I just refactored this PR into a PR against cloudaux:

https://github.com/Netflix-Skunkworks/cloudaux/pull/4/files

I'll make a new PR against SM to replace the current S3 watcher and use the cloudaux stuff.

```
from cloudaux.orchestration.aws.s3 import get_bucket

conn = dict(
    account_number='000000000000',
    assume_role='SecurityMonkey')

bucket = get_bucket('MyS3Bucket', **conn)

print(json.dumps(bucket, indent=2, sort_keys=True))

{
  "Arn": "arn:aws:s3:::MyS3Bucket", 
  "Grants": {
    "cloudaux_grantee": [
      "FULL_CONTROL"
    ]
  }, 
  "LifecycleRules": [
    {
      "expiration": {
        "days": 365
      }, 
      "id": "deleteoldstuff", 
      "prefix": "/doesntactuallyexist", 
      "status": "Enabled"
    }
  ], 
  "Logging": {
    "enabled": true, 
    "grants": [], 
    "prefix": "logs/", 
    "target": "MyS3LoggingBucket"
  }, 
  "Policy": {
    "Statement": [
      {
        "Action": "s3:GetObject", 
        "Effect": "Allow", 
        "Principal": {
          "AWS": "*"
        }, 
        "Resource": "arn:aws:s3:::MyS3Bucket/*", 
        "Sid": "AddPerm"
      }
    ], 
    "Version": "2008-10-17"
  }, 
  "Tags": {
    "tagkey": "tagvalue"
  }, 
  "Versioning": {
    "Versioning": "Enabled"
  }, 
  "_version": 1
}
```

**Comment by monkeysecurity** [comment]
Hey @aebie and @zollman,

Could you take a look at #449.  Let me know if you see any issues with that implementation.  It's using much of this same code, but refactored into cloudaux.

**Comment by aebie** [comment]
@monkeysecurity the code looks right. If it can wait until Monday I can pull it down and test it, got some stuff I need to finish before the weekend today.

**Comment by monkeysecurity** [comment]
Will do.  Thanks @aebie.

**Comment by monkeysecurity** [comment]
Hey @aebie, @mikegrima just now finished updating the CloudAux S3 tech:

https://github.com/Netflix-Skunkworks/cloudaux/pull/6

He added a bunch of new sections.  Here's the full list:

- Website configuration
- Acceleration Configuration
- Bucket ownership information (Comes from the ACL call)
- Bucket ACLs
- Bucket Policies
- Bucket Creation Date (Comes from listing all buckets as outlined here: boto3 API. We may have to skip this, since it is an expensive operation.) (Addressed in #6 as an optional field)
- Replication Configuration
- Logging
- Tags
- Region
- CORS Rules
- Notification Configuration
- Versioning

I'll merge and push an updated version to pypi once you give me the okay.

**Comment by aebie** [comment]
@monkeysecurity I did get time to pull down cloudaux and start to get familiar with it. S3 appears to work although I did not get a chance to pull down PR 449 to test it. I think this is OK because the code looks fine, and I don't want to hold up the process, so I would say go ahead and merge it. If we find any issues when merging in your latest develop we can always do another PR.

**Comment by monkeysecurity** [comment]
replaced by #449

**Pull request closed without merging**
