### PR TITLE
Update Scheduler to use APScheduler v3

### PR DESCRIPTION
**Pull request by ollytheninja**

### CODE REVIEW

**Comment by cstewart87** [comment]
Hey @ollytheninja, are you using this feature in your security monkey stack?  Wondering if it's working to the point where I can pull it in as well.  Tired of working around the scheduler restarts when working with accounts 😞

**Comment by ollytheninja** [comment]
Hi @cstewart87,
Yes, I run this in production and it's working well for us.
I've noticed some syncing issues where one server will pick up all of the jobs and the other sits idle.
I haven't had time to spend on Security Monkey in the last few months, I am starting to have that time again and will be looking to fine tune a bit more and then getting it merged.

**Comment by monkeysecurity** [comment]
@ollytheninja's back!!

**Comment by monkeysecurity** [comment]
I should have merged this in a while ago. Unfortunately, now the codebase has drifted quite a bit. I'm going to close the ticket.

**Comment by ollytheninja** [comment]
@monkeysecurity I've regressed this in our codebase as well and will reimplement

**Pull request closed without merging**
