### PR TITLE
Flask-Security-Fork is merged in Flask-Security

### PR DESCRIPTION
**Pull request by jirikuncar**

### CODE REVIEW

**Comment by mikegrima** [comment]
Hello! I wanted to circle back on this. Can you rebase with the latest and re-submit this?

**Comment by mikegrima** [comment]
Unfortunately, this appears to break the build.

**Comment by jirikuncar** [comment]
I don't see how is it connected with Flask-Security:
```
File "/home/travis/build/Netflix/security_monkey/security_monkey/__init__.py", line 246, in <module>
    from security_monkey.sso.views import mod as sso_bp
  File "/home/travis/build/Netflix/security_monkey/security_monkey/sso/views.py", line 458, in <module>
    api.add_resource(AzureAD, '/auth/aad', endpoint='aad')
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/Flask_RESTful-0.3.3-py2.7.egg/flask_restful/__init__.py", line 387, in add_resource
    self._register_view(self.app, resource, *urls, **kwargs)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/Flask_RESTful-0.3.3-py2.7.egg/flask_restful/__init__.py", line 417, in _register_view
    if endpoint in app.view_functions.keys():
AttributeError: 'Blueprint' object has no attribute 'view_functions'
```

**Comment by mikegrima** [comment]
Could it be related to the upgraded Flask version?

**Comment by jirikuncar** [comment]
@mikegrima it looks like it has been fixed in [Flask-RESTful](https://github.com/flask-restful/flask-restful/blob/8c8c727f5cdb8942e0422f9f17f9fd95cbdc82f3/flask_restful/__init__.py#L433-L439).

**Pull request merged**
