### PR TITLE
Add Watcher configuration

### PR DESCRIPTION
**Pull request by kalpatel01**
Type: generic-large-feature

Why is this change necessary?
We've run into instances where we have wanted to reconfigure watcher run
intervals to improve performance or even remove watchers that were
causing problems. Currently this requires logging into the server and
physically changing the code

This change addresses the need by:
Provides a Watcher Config page in Settings and an api where a user can
configure the run interval and the active flag

Potential Side Effects:
No known side effects

### CODE REVIEW

**Comment by monkeysecurity** [comment]
Looks like this depends on #528

**Comment by cstewart87** [comment]
@monkeysecurity - yes, looks like there's a conflict as well that we need to resolve.  Will submit an update as soon as possible.

**Comment by cstewart87** [comment]
#528 should be good to go now, but we're still working out updates to this PR.  Hope to have them out soon with conflicts resolved.

**Comment by aebie** [comment]
The broke test is related to https://github.com/Netflix/security_monkey/commit/c666a012ec65a4ffcb878d148e2af33022c42afd. The test reporter was not updated to remove the deprecated fields. For some reason, this causes the tests to hang instead of fail.

**Comment by aebie** [comment]
See issue https://github.com/Netflix/security_monkey/issues/556

**Comment by monkeysecurity** [comment]
Merged in #559

**Pull request closed without merging**
