### PR TITLE
Added support for SSO OneLogin

### PR DESCRIPTION
**Pull request by crruthe**

### CODE REVIEW

**Comment by monkeysecurity** [comment]
Somebody comments their code!

Let me know if this is ready to start reviewing.

**Comment by crruthe** [comment]
Ah don't be fooled, majority of the comments are sampled from the onelogin saml python library :)
I think I managed to get all the dependencies sorted. I'll kick off a full test again on Monday to be sure, but code review wise it should all be there and is ready.

**Comment by pitbulk** [comment]
Update to python [2.2.0](https://pypi.python.org/pypi/python-saml), this version includes a security patch that contains extra validations that will prevent signature wrapping attacks and other security improvements.


I highly recommended to use it instead previous versions.

**Comment by monkeysecurity** [comment]
@crruthe - Could you bump python-saml to 2.2.0 as @pitbulk recommends?

**Comment by crruthe** [comment]
@pitbulk @monkeysecurity good call, done

**Pull request merged**
