### PR TITLE
Fix for issue 1150

### PR DESCRIPTION
**Pull request by macedogm**
Fixed issue https://github.com/Netflix/security_monkey/issues/1150

### CODE REVIEW

**Comment by mikegrima** [comment]
LGTM.

**Review by mikegrima — CHANGES_REQUESTED** [review]
`query = query.join((Account, Account.id == Item.account_id))` <-- this is still needed, but only once.

Probably need to add a boolean to indicate that this is needed, and then at the end of all the `if` statements, add in another that adds it in if the check is `True`.

**Comment by macedogm** [comment]
Did the new fix as requested. Hope that it is in a way that you are able approve. Sorry for any bad coding design.

**Comment by mikegrima** [comment]
@macedogm It looks the same.

**Comment by macedogm** [comment]
Sorry. Will open a new PR.

**Pull request closed without merging**
