### PR TITLE
Find and register watchers and auditors

### PR DESCRIPTION
**Pull request by DenverJ**
This addresses some of the points in #157 - namely watchers and auditors as pluggable modules which allows people to drop in their own modules and have multiple auditors related to one watcher/technology. It all reduces the amount of boilerplate code required to set up a new 'monitor'.

This finds all watchers and auditors under the relevant paths and ignores any modules in the respective 'custom' folders.

The watchers and auditors use meta-classes to register themselves as valid watchers/auditors.

### CODE REVIEW

**Comment by monkeysecurity** [comment]
This looks promising.  It's taking some time to review because it's a larger change.  I want to make sure @DenverJ knows this PR is appreciated.

**Comment by cstewart87** [comment]
Any plans to incorporate these changes any time soon?  Also, is there any accompanying documentation for how to implement new watchers/auditors using this pluggable framework? 

(BTW - :+1: for these changes!)

**Comment by huntergregal** [comment]
This would be a huge improvement. I would very much like to see this incorporated into the master branch. It would streamline development and make it easier for people to contribute.

So... bump :100:  :)

**Comment by aebie** [comment]
Is there any timeline for merging this? I have been working on something similar but would very much prefer to pull down from master.

**Comment by monkeysecurity** [comment]
Hey @DenverJ - Thanks a bunch for this PR.  We ended up merging it in with PR #405 & #410.

It took a while, but I'm super happy with it.

**Pull request closed without merging**
