### PR TITLE
Fix TypeError when not granted es:ListDomainNames

### PR DESCRIPTION
**Pull request by mark-ignacio**
* Make ElasticSearch watcher check for None before doing an tuple unpack on ES domain enumeration

### CODE REVIEW

**Comment by mikegrima** [comment]
Hello @mark-ignacio . I'm trying to understand the circumstances on the exception that is being raised.

Could you output what the `**kwargs` are  being passed into that method?

**Comment by mark-ignacio** [comment]
Sure - got this with `pdb.set_trace()` and censored all of the fun stuff.

```
{'account_name': u'specialsnowflake',
 'account_number': u'[nope]',
 'assume_role': 'SecurityMonkey',
 'assumed_role': {u'AssumedRoleUser': {u'Arn': 'arn:aws:sts::[nope]:assumed-role/SecurityMonkey/secmonkey',
                                       u'AssumedRoleId': '[nope]:secmonkey'},
                  u'Credentials': {u'AccessKeyId': '[nope]',
                                   u'Expiration': datetime.datetime(2017, 10, 24, 0, 9, 59, tzinfo=tzlocal()),
                                   u'SecretAccessKey': '[nope]',
                                   u'SessionToken': '[nope]'},
                  'ResponseMetadata': {'HTTPHeaders': {'content-length': '1059',
                                                       'content-type': 'text/xml',
                                                       'date': 'Mon, 23 Oct 2017 23:09:58 GMT',
                                                       'x-amzn-requestid': '[nope]'},
                                       'HTTPStatusCode': 200,
                                       'RequestId': '[nope]',
                                       'RetryAttempts': 0}},
 'exception_map': {('elasticsearchservice', u'fbsec', u'ap-northeast-1'): BotoConnectionIssue()},
 'index': 'elasticsearchservice',
 'region': u'ap-northeast-1'}
```
...should `BotoConnectionIssue` be there? :sweat_smile:

**Comment by mikegrima** [comment]
Would like to know more about that `BotoConnectionIssue`, and why a `NoneType` is being raised.

**Comment by mark-ignacio** [comment]
As for why None is getting raised, it's because the [`record_exception` decorator ends with a `store_exception()`](https://github.com/Netflix/security_monkey/blob/f9dfe698ddb52c41c882114c6ad497b2e0185d37/security_monkey/decorators.py#L94-L116) call when the decorated function raises.

As for `BotoConnectionIssue`, here's the actual exception message:

    (Pdb) pp kwargs['exception_map'].values()[0].connection_message
    'An error occurred (AccessDeniedException) when calling the ListDomainNames operation: User: arn:aws:sts::[nope]:assumed-role/SecurityMonkey/secmonkey is not authorized to perform: es:ListDomainNames on resource: arn:aws:es:ap-northeast-1:[nope]:domain/*'

Looks like the root cause of this whole shebang is an IAM misconfiguration in the account. It was using a `SecurityMonkeyReadOnly` policy that was created in 2015 shown here:

```
{
    "Statement": [
        {
            "Action": [
                "cloudwatch:Describe*",
                "cloudwatch:Get*",
                "cloudwatch:List*",
                "ec2:Describe*",
                "elasticloadbalancing:Describe*",
                "iam:List*",
                "iam:Get*",
                "route53:Get*",
                "route53:List*",
                "rds:Describe*",
                "s3:GetBucketAcl",
                "s3:GetBucketCORS",
                "s3:GetBucketLocation",
                "s3:GetBucketLogging",
                "s3:GetBucketPolicy",
                "s3:GetBucketVersioning",
                "s3:GetLifecycleConfiguration",
                "s3:ListAllMyBuckets",
                "sdb:GetAttributes",
                "sdb:List*",
                "sdb:Select*",
                "ses:Get*",
                "ses:List*",
                "sns:Get*",
                "sns:List*",
                "sqs:GetQueueAttributes",
                "sqs:ListQueues",
                "sqs:ReceiveMessage"
            ],
            "Effect": "Allow",
            "Resource": "*"
        }
    ]
}
```

Does this look like an old policy that would've been in the Github project in 2015?

**Comment by mikegrima** [comment]
Hi @mark-ignacio . Yes, that's an old policy. Please apply the latest policy [documented here](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_aws.md#creating-securitymonkey-role) in step 5. We've added quite a few more technologies since then :)

Also, tell Ben I said hi :)

**Comment by mikegrima** [comment]
@mark-ignacio to fix up this PR, can you add in the proper decorator args to `record_exception`?

Here is an example
https://github.com/Netflix/security_monkey/blob/develop/security_monkey/cloudaux_watcher.py#L76-L77

**Comment by D4rk4** [comment]
Please merge

**Comment by mark-ignacio** [comment]
Circling back to this - sorry to take a while! I had to shuffle some stuff around to reproduce.

I copypasted that, but didn't work. Looking further into it, there doesn't seem to be anything in `record_exception` that allows it to adhere to the wrapped function signature. The code block here implicitly returns None when the original returns a tuple:

https://github.com/Netflix/security_monkey/blob/53f2fb18e01c52add014b15def70e223c099a025/security_monkey/decorators.py#L94-L116

I could add an optional kwarg to `record_exception` to allow it to return `(None, [])`, but IMO it'll make it messier than just bailing out with a return statement.

**Comment by mikegrima** [comment]
@mark-ignacio Curious why that isn't working -- we use the same code throughout (without issues).

**Comment by mark-ignacio** [comment]
To reproduce I loaded up the old, bad IAM policy from above and ran `monkey find_changes -a profile`.

Maybe you've rightfully given Security Monkey `es:ListDomainNames` everywhere it's running?

**Comment by mikegrima** [comment]
I'm going to try running it with that being the case.  However, the decorator needs to be fixed.

**Comment by mikegrima** [comment]
@mark-ignacio Figured out what needs to be fixed.  I'm going to merge this in (needs to be there), and make a quick follow-up PR to fully iron out the issue.

**Comment by mikegrima** [comment]
#888 is the follow-up fix.

**Pull request merged**
