### PR TITLE
Adding index to region. Dropping unused item.cloud.

### PR DESCRIPTION
**Pull request by monkeysecurity**
Depends on PR #408 being merged first because of the Alembic upgrade.

### CODE REVIEW

**Comment by monkeysecurity** [comment]
Hold off.  

The `db migrate` script is asking to do some modifications to the exceptions table:

```
    op.drop_constraint(u'exceptions_tech_id_fkey', 'exceptions', type_='foreignkey')
    op.drop_constraint(u'exceptions_item_id_fkey', 'exceptions', type_='foreignkey')
    op.drop_constraint(u'exceptions_account_id_fkey', 'exceptions', type_='foreignkey')
    op.create_foreign_key(None, 'exceptions', 'account', ['account_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'exceptions', 'item', ['item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'exceptions', 'technology', ['tech_id'], ['id'], ondelete='CASCADE')
```

Trying to figure out why the previous Alembic migration didn't properly handle the `ondelete='CASCADE'`, and if this is something we should add to this upgrade.

**Comment by mikegrima** [comment]
Found the error in the tests. The tests assume that the `Item` is attached to an account type.  Updating now.

**Comment by mikegrima** [comment]
Rebased with `develop`. Testing now...

**Comment by mikegrima** [comment]
Passed ✅

**Pull request merged**
