### PR TITLE
Fix for issue #966.

### PR DESCRIPTION
**Pull request by senorcinco**
After applying patch:

```
$ monkey create_user "user.name@example.com" "Justify"
Password: 
Confirm Password:

$ monkey create_user "user.name@example.com" "Justify"
[+] Updating existing user
Password: 
Confirm Password:
$
```

### CODE REVIEW

**Comment by mikegrima** [comment]
Hello @senorcinco ! Hope it's not too much to ask, but can you write a unit test for this?

Here is a good example of testing the manage commands: https://github.com/Netflix/security_monkey/blob/94eeadd55b59cdc18ca7bbdfea7722df81e7f468/security_monkey/tests/utilities/test_account_utils.py#L34

**Comment by senorcinco** [comment]
Hi @mikegrima .  I think I'm in over my head on writing a unit test.  I took a swing at it, but it doesn't like my attempt to mock the password prompt.  I could be way off, but do you have any pointers?

**Comment by mikegrima** [comment]
I'll take a look soon.

**Comment by mikegrima** [comment]
@senorcinco Try: `@patch('security_monkey.manage.prompt_pass', return_value='r3s3tm3!')`
^^ You need to patch the `manage.py`'s instance of `promot_pass` (this is a very common mistake in mocking Python -- I make it all the time)

**Comment by mikegrima** [comment]
I actually went ahead and fixed this.  I'm going to submit a follow-up PR.

**Comment by mikegrima** [comment]
See: https://github.com/Netflix/security_monkey/pull/970/files

**Pull request merged**
