### PR TITLE
Add a VPN Connection watcher and auditor

### PR DESCRIPTION
**Pull request by AlexCline**
VPN connections will now be monitored and audited. The following attributes are collected (beyond the basics):

* Type
* State
* Tunnels
  * Status (up/down)
  * Route Count
  * Outside IP
  * Last Status Change
  * Status Message
* VPN Gateway ID
* Customer Gateway ID

Also included is an auditor that will check for tunnels whose status is not UP, and a test file.

New IAM permissions are needed for this change:

ec2:DescribeVpnConnections

### CODE REVIEW

**Comment by AlexCline** [comment]
This might not be testable without another peer VPN to connect to. :-/

**Comment by monkeysecurity** [comment]
@mikegrima - What should we do for a test here?

Does `moto` have support?

**Comment by mikegrima** [comment]
Not sure if `moto` has support or not (you can try?).

If not, there's always the stubber: http://botocore.readthedocs.io/en/latest/reference/stubber.html

**Comment by monkeysecurity** [comment]
Adding `needs work` label as the test is failing.

Possible Solutions:
- Mock out the service
- Delete the test

Also worth considering:
- We're starting to move watchers out of the security_monkey code base and into the cloudaux library.

**Comment by monkeysecurity** [comment]
Thanks.  I'll merge this in and add `ec2:DescribeVpnConnections` to the docs.

**Pull request merged**
