### PR TITLE
Add support for filtering by item score.

### PR DESCRIPTION
**Pull request by monkeysecurity**
To fulfill Issue #436

### CODE REVIEW

**Comment by cstewart87** [comment]
I've been testing out this new filter and running into errors.  When I input a value and click search, the fields for both new filters (min and min justified score) are populated with "null" and the table displays the following error message:

```
Error loading resource from API. Error: <HTTP 400: { "message": { "min_score": "invalid literal for int() with base 10: 'null'" } } >
```

Any suggestions for resolving this issue?

**Comment by monkeysecurity** [comment]
Interesting. Are you using Chrome? Latest commit on the dev branch?

**Comment by cstewart87** [comment]
Yes and yes.  Potentially something on my end, troubleshooting now, but wanted to pose the question in case it was a known issue or something you may have come across in your development.

**Comment by monkeysecurity** [comment]
Nope. Haven't seen it before.

**Comment by cstewart87** [comment]
@monkeysecurity - FYI, I was able to resolve the issue.  Turns out, some of the additions made to dart/lib/component/search_bar_component/search_bar_component.dart were reverted during our merge.  Adding all of the changes from this commit back to the file resolved the issue.

**Pull request merged**
