### PR TITLE
Adds separate ingress v. egress checks for 0.0.0.0/0 #239

### PR DESCRIPTION
**Pull request by snixon**
Added distinct checks for ingress vs egress any rules in security groups.
I also bumped up the severity of the ingress 0.0.0.0/0 check to 10.  Hopefully this helps out with #239

### CODE REVIEW

**Comment by monkeysecurity** [comment]
Thanks @snixon. Since you added `check_securitygroup_ingress_any` and `check_securitygroup_egress_any`, shouldn't you also delete `check_securitygroup_any` ?

**Comment by snixon** [comment]
Hi @monkeysecurity 
I was thinking that some users might like having that check in place as a catch all.  My workflow is to disable the combined check in auditor settings and use the other two to report on.  But we could definitely remove it entirely if it's not useful anymore.

**Comment by monkeysecurity** [comment]
Yeah - let's remove `check_securitygroup_any` and keep the other two.

Also, could you resubmit the PR against the develop branch?  I'm okay merging into master and then merging back into develop, but its easier for me to just merge directly into develop.

I'll be releasing v0.5.0 to master this week.

**Comment by snixon** [comment]
No problem, opened a new PR against develop.

**Pull request closed without merging**
