### PR TITLE
Feature: Add user authentication using AzureAD as an SSO provider

### PR DESCRIPTION
**Pull request by jleaniz**
This patch adds support for user authentication vua Azure Active Directory OpenID Connect.

Note that this will only authenticate the user by providing an id_token (which is verified) but will not check for any authorization grants (i.e. group membership)

### CODE REVIEW

**Comment by monkeysecurity** [comment]
Hey @jleaniz - I just spoke to @mikegrima and we think additional SSO options are awesome and welcome.

We don't have a way to test SSO solutions that we don't have deployed.  Would you be willing to write some unit tests for the `sso.py` module to cover the AzureAD stuff?  I realize we don't have any unittests for the other SSO implementations yet, but we think we're going to start needing some as we're only familiar with our own SSO solution.

**Comment by jleaniz** [comment]
hey @monkeysecurity, i'm going to try to write the unit tests for AzureAD. I'll report back when i have an update on that. Do you want to add that to this pull request or shall we create a separate one where we can add unit tests for the other SSO implementations as well?

**Comment by monkeysecurity** [comment]
Let's add it to this one.

**Comment by monkeysecurity** [comment]
oops - accidentally closed PR - reopening

**Comment by monkeysecurity** [comment]
@jleaniz - Are the unittests imminent, or should I merge what we have now?

**Comment by jleaniz** [comment]
Sorry for the delay, give me until Friday,  Should have basic unittests for AAD

**Comment by jleaniz** [comment]
Unit test for Azure id_token validation is committed. Not sure why the CI check failed, seems to be on some part of the code i didn't touch.

**Comment by monkeysecurity** [comment]
@jleaniz - looks like it's failing on `test_kms.py`, which was fixed on `develop`.

Something like this should fix it.

```bash
git checkout -b netflix-develop
git pull git://github.com/netflix/security_monkey.git netflix-develop
git checkout develop
git merge --no-ff netflix-develop
git push
```

**Comment by jleaniz** [comment]
Hey @monkeysecurity i merged with the latest coded from netflix 'develop' but build fails with:

IOError: [Errno 21] Unable to load configuration file (Is a directory): 
 /home/travis/build/Netflix/security_monkey'
The command "monkey db upgrade" failed and exited with 1 during .

**Pull request merged**
